"use strict";
console.log('hello, world');
const $heading = document.querySelector('h1');
console.log('heading', $heading);
console.dir('heading', $heading);
const $id = document.querySelector('#explanation');
console.log('id', $id);
console.dir('id', $id);
const $hint = document.querySelector('.hint');
console.log('hint', $hint);
console.dir('hint', $hint);
const $pVariable = document.querySelectorAll('p');
console.log('p', $pVariable);
const $exampleLink = document.querySelectorAll('.example-link');
console.log('example link', $exampleLink);
