'use strict';
const width = 10;
const height = 4;
const area = width * height;
console.log('value of area:', area);
console.log('typeof area:', typeof area);
const bill = 12.5;
const payment = 20.48;
const change = payment - bill;
console.log('value of change:', change);
console.log('typeof change:', typeof change);
const quizzes = 85;
const midterm = 95;
const final = 88;
const grade = (quizzes + midterm + final) / 3;
console.log('value of grade:', grade);
console.log('typeof grade:', typeof grade);
const firstName = 'Ryan';
const lastName = 'Garcia';
const fullName = firstName + ' ' + lastName;
console.log('value of fullName:', fullName);
console.log('typeof fullName:', typeof fullName);
const pH = 5;
const isAcidic = pH < 7;
console.log('value of isAcidic:', isAcidic);
console.log('typeof isAcidic:', typeof isAcidic);
const headCount = 47;
const isSparta = headCount == 300;
console.log('value of isSparta:', isSparta);
console.log('typeof isSparta:', typeof isSparta);
let motto = fullName;
motto += ' is the GOAT';
console.log('value of motto:', motto);
console.log('typeof motto:', typeof motto);
